export type NASA_PHOTOS_FETCH_LOADING = 'NASA_PHOTOS_FETCH_LOADING'
export type NASA_PHOTOS_FETCH_SUCCESS = 'NASA_PHOTOS_FETCH_SUCCESS'
export type NASA_PHOTOS_FETCH_ERROR = 'NASA_PHOTOS_FETCH_ERROR'
export type NASA_PHOTOS_ADD_FAVOURITE = 'NASA_PHOTOS_ADD_FAVOURITE'
